function qp = KinematicVector(in1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.

%    08-Feb-2021 13:54:24



p1 = in1(7,:);

p2 = in1(8,:);

p3 = in1(9,:);

th = in1(3,:);

t2 = pi.*(1.0./3.0);

t3 = t2+th;

qp = [p1;p2;p3;p3.*(-1.25e2./4.3e1)-p2.*cos(th).*(5.0e2./4.3e1)+p1.*sin(th).*(5.0e2./4.3e1);p3.*(-1.25e2./4.3e1)+p2.*cos(th-pi.*(1.0./3.0)).*(5.0e2./4.3e1)+p1.*cos(th+pi.*(1.0./6.0)).*(5.0e2./4.3e1);p3.*(-1.25e2./4.3e1)+p2.*cos(t3).*(5.0e2./4.3e1)-p1.*sin(t3).*(5.0e2./4.3e1)];

end